import { addIcons } from 'ionicons';
import {
  add,
  closeCircle,
  trash,
  create,
  book,
  bookOutline,
  person,
  settings,
  home,
  libraryOutline,
  constructOutline,
  swapHorizontal,
  receiptOutline,
  personCircleOutline,
  homeOutline,
  logOutOutline,
  peopleOutline,
  ellipsisHorizontalOutline,
  eyeOutline,
  createOutline,
  searchOutline,
  checkmarkOutline,
  arrowBack,
  logInOutline,
  personAddOutline,
  locationOutline,
  timeOutline,
  callOutline,
  mailOutline,
  notificationsOutline,
  arrowForwardOutline,
  scanOutline,
  calendarOutline,
  returnDownBackOutline,
  reloadOutline,
  filterOutline,
  warningOutline,
  caretDownOutline,
  reorderThreeOutline,
} from 'ionicons/icons';

export const iconosApp = {
  'home-outline': homeOutline,
  'library-outline': libraryOutline,
  'construct-outline': constructOutline,
  'swap-horizontal': swapHorizontal,
  'receipt-outline': receiptOutline,
  'person-circle-outline': personCircleOutline,
  settings: settings,
  'log-out-outline': logOutOutline,
  'log-in-outline': logInOutline,
  'people-outline': peopleOutline,
  'ellipsis-horizontal-outline': ellipsisHorizontalOutline,
  home: home,
  add: add,
  'close-circle': closeCircle,
  trash: trash,
  create: create,
  book: book,
  'book-outline': bookOutline,
  person: person,
  'person-add-outline': personAddOutline,
  'eye-outline': eyeOutline,
  'create-outline': createOutline,
  'search-outline': searchOutline,
  'checkmark-outline': checkmarkOutline,
  'arrow-back': arrowBack,
  'location-outline': locationOutline,
  'time-outline': timeOutline,
  'call-outline': callOutline,
  'mail-outline': mailOutline,
  'notifications-outline': notificationsOutline,
  'arrow-forward-outline': arrowForwardOutline,
  'scan-outline': scanOutline,
  'calendar-outline': calendarOutline,
  'return-down-back-outline': returnDownBackOutline,
  'reload-outline': reloadOutline,
  'filter-outline': filterOutline,
  'warning-outline': warningOutline,
  'caret-down-outline': caretDownOutline,
  'reorder-three-outline': reorderThreeOutline,
};

export type IconosAppType = keyof typeof iconosApp;

export const registrarIconos = () => {
  addIcons(iconosApp);
};
